import argparse
import itertools
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import rankdata
import torch
from tqdm.auto import tqdm


def parse_arguments():
    parser = argparse.ArgumentParser(description="Plot Semantically Sorted RDMs")

    parser.add_argument(
        "--metadata_csv",
        type=Path,
        default=Path("../data/processed/things_metadata.csv"),
        help="Path to the generated metadata CSV file.",
    )
    parser.add_argument(
        "--semantic_csv",
        type=Path,
        default=Path("../data/processed/semantic_ordering.csv"),
        help="Path to the semantic ordering CSV generated by the 1.x script.",
    )
    parser.add_argument(
        "--activations_dir",
        type=Path,
        default=Path("../data/processed/activations"),
        help="Directory containing the extracted ANN .npy features.",
    )
    parser.add_argument(
        "--out_dir",
        type=Path,
        default=Path("../data/figures/rdms"),
        help="Directory to save the generated RDM plots.",
    )
    parser.add_argument(
        "--monkeys",
        nargs="+",
        type=str,
        default=["monkeyF", "monkeyN"],
        help="List of monkey subjects to plot (e.g., monkeyF monkeyN).",
    )
    parser.add_argument(
        "--rois",
        nargs="+",
        type=str,
        default=["V1", "V4", "IT"],
        help="List of ROIs to process (e.g. IT V1 V4).",
    )
    parser.add_argument(
        "--noise_levels",
        nargs="+",
        type=float,
        default=[0.1, 0.25, 0.50, 0.75],
        help="List of Stable Diffusion noise levels.",
    )

    return parser.parse_args()


def load_sorted_representations(monkey, roi, noise_level, args):
    df = pd.read_csv(args.metadata_csv)
    semantic_df = pd.read_csv(args.semantic_csv)

    subset_df = df[(df["monkey"] == monkey) & (df["ROI"] == roi)].copy()
    if subset_df.empty:
        raise ValueError(f"No metadata found for {monkey} - {roi}")

    subset_df = subset_df.merge(
        semantic_df[["folder_name", "semantic_sort_index"]],
        left_on="category",
        right_on="folder_name",
        how="inner",
    )
    subset_df = subset_df.sort_values(by=["semantic_sort_index", "image_id"])

    response_file_relative = subset_df.iloc[0]["response_file_name"]
    bio_file_path = args.metadata_csv.parent / response_file_relative

    if not bio_file_path.exists():
        raise FileNotFoundError(f"Biological responses not found at {bio_file_path}")

    bio_features = np.load(bio_file_path)
    response_indices = subset_df["response_file_index"].values.astype(int)
    bio_matrix = bio_features[response_indices]

    image_ids = subset_df["image_id"].values.astype(int)
    noise_rounded = round(noise_level, 2)
    ai_noisy_path = args.activations_dir / f"sd15_mid_block_noise_{noise_rounded:.2f}.npy"

    if not ai_noisy_path.exists():
        raise FileNotFoundError(f"ANN activations not found at {ai_noisy_path}")

    ai_noisy_features = np.load(ai_noisy_path, mmap_mode="r")
    ai_noisy_matrix = ai_noisy_features[image_ids]

    return ai_noisy_matrix, bio_matrix


def calc_rdm_correlation_torch(x):
    x_centered = x - x.mean(dim=1, keepdim=True)
    x_norm = x_centered / torch.norm(x_centered, p=2, dim=1, keepdim=True)
    sim = torch.mm(x_norm, x_norm.t())
    return 1.0 - sim


def transform_to_percentile_rdm(rdm):
    n = rdm.shape[0]
    i_upper, j_upper = np.triu_indices(n, k=1)

    ranks = rankdata(rdm[i_upper, j_upper])
    percentiles = (ranks - 1) / (len(ranks) - 1)

    percentile_rdm = np.zeros_like(rdm)
    percentile_rdm[i_upper, j_upper] = percentiles
    percentile_rdm[j_upper, i_upper] = percentiles
    return percentile_rdm


def process_combination(monkey, roi, noise_level, args, device):
    try:
        ai_noisy_matrix, bio_matrix = load_sorted_representations(monkey, roi, noise_level, args)
    except (ValueError, FileNotFoundError):
        return False

    with torch.no_grad():
        t_bnn = torch.tensor(bio_matrix, dtype=torch.float32, device=device)
        t_ann_noisy = torch.tensor(ai_noisy_matrix, dtype=torch.float32, device=device)

        rdm_bnn = calc_rdm_correlation_torch(t_bnn).cpu().numpy()
        rdm_ann_noisy = calc_rdm_correlation_torch(t_ann_noisy).cpu().numpy()

    rdm_ann_pct = transform_to_percentile_rdm(rdm_ann_noisy)
    rdm_bnn_pct = transform_to_percentile_rdm(rdm_bnn)

    fig, axes = plt.subplots(1, 2, figsize=(12, 5.5))
    subject_name = monkey.replace("monkey", "")

    fig.suptitle(
        f"Representational Dissimilarity Matrices (Rank-Transformed Percentiles)\nMacaque {subject_name} {roi} vs. Stable Diffusion",
        fontsize=15,
        fontweight="bold",
        y=1.02,
    )

    cmap = "viridis"
    vmin, vmax = 0.0, 1.0

    _ = axes[0].imshow(rdm_ann_pct, cmap=cmap, vmin=vmin, vmax=vmax)
    axes[0].set_title(f"Stable Diffusion (Noise: {noise_level:g})", fontsize=12, pad=10)
    axes[0].axis("off")

    im2 = axes[1].imshow(rdm_bnn_pct, cmap=cmap, vmin=vmin, vmax=vmax)
    axes[1].set_title(f"Macaque {subject_name} ({roi} Cortex)", fontsize=12, pad=10)
    axes[1].axis("off")

    cbar = fig.colorbar(im2, ax=axes, fraction=0.03, pad=0.04, shrink=0.75, aspect=20)
    cbar.set_label(
        "Dissimilarity Percentile (0 = Most Similar, 1 = Least)",
        rotation=270,
        labelpad=20,
        fontsize=10,
    )

    out_file = args.out_dir / f"rdms_{monkey}_{roi}_noise_{noise_level:.2f}.png"
    fig.savefig(out_file, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    return True


def main():
    args = parse_arguments()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    if not args.metadata_csv.exists() or not args.semantic_csv.exists():
        raise FileNotFoundError(
            "Missing metadata or semantic ordering CSV. Ensure 1.x scripts are completed."
        )

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "mps"
        if torch.backends.mps.is_available()
        else "cpu"
    )
    print(f"Compute Device: {device}\n")

    combinations = list(itertools.product(args.monkeys, args.rois, args.noise_levels))
    progress_bar = tqdm(combinations, desc="Generating RDMs...", unit="plot")

    success_count = 0
    for monkey, roi, noise_level in progress_bar:
        progress_bar.set_description(f"[{monkey} | {roi} | Noise: {noise_level}]")

        success = process_combination(monkey, roi, noise_level, args, device)
        if success:
            success_count += 1
            progress_bar.set_postfix(status="Saved")
        else:
            progress_bar.set_postfix(status="Skipped (No Data)")

    print(f"\nSuccessfully generated {success_count} RDM figures in: {args.out_dir}")


if __name__ == "__main__":
    main()
